"use client";

import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { CalendarClock, CheckSquare, FileText, Play, Plus, Sparkles, Users } from "lucide-react";
import { Modal } from "@/components/app/Modal";
import { CallRoom } from "@/components/communication/CallRoom";
import { usePulseStore } from "@/stores/usePulseStore";

const button = "inline-flex items-center justify-center gap-2 rounded-lg border border-[var(--border-subtle)] bg-[var(--card-bg)] px-3 py-2 text-xs font-semibold text-[var(--text-secondary)] transition hover:border-[var(--border-strong)] hover:text-[var(--text-primary)] disabled:cursor-not-allowed disabled:opacity-50";

export function MeetingsHub() {
  const router = useRouter();
  const params = useSearchParams();
  const meetings = usePulseStore((state) => state.meetings);
  const members = usePulseStore((state) => state.members);
  const scheduleMeeting = usePulseStore((state) => state.scheduleMeeting);
  const startMeeting = usePulseStore((state) => state.startMeeting);
  const endMeeting = usePulseStore((state) => state.endMeeting);
  const saveMeetingNotes = usePulseStore((state) => state.saveMeetingNotes);
  const generateMeetingAgenda = usePulseStore((state) => state.generateMeetingAgenda);
  const createMeetingFollowUpTasks = usePulseStore((state) => state.createMeetingFollowUpTasks);
  const [selectedId, setSelectedId] = useState(params.get("meeting") ?? meetings[0]?.id);
  const [activeCallId, setActiveCallId] = useState<string | null>(null);
  const [createOpen, setCreateOpen] = useState(false);
  const [title, setTitle] = useState(""); const [project, setProject] = useState(""); const [agenda, setAgenda] = useState(""); const [when, setWhen] = useState("");
  const selected = meetings.find((meeting) => meeting.id === selectedId) ?? meetings[0];

  useEffect(() => { const requested = params.get("meeting"); if (requested && meetings.some((meeting) => meeting.id === requested)) setSelectedId(requested); }, [meetings, params]);
  const groups = useMemo(() => ({ Upcoming: meetings.filter((meeting) => !meeting.status || meeting.status === "Upcoming"), "In progress": meetings.filter((meeting) => meeting.status === "In progress"), Completed: meetings.filter((meeting) => meeting.status === "Completed") }), [meetings]);

  function select(id: string) { setSelectedId(id); router.replace(`/app/meetings?meeting=${id}`); }
  function join(id: string) { const callId = startMeeting(id); if (callId) { setSelectedId(id); setActiveCallId(callId); router.replace(`/app/meetings?meeting=${id}`); } }
  function create(event: FormEvent) { event.preventDefault(); const id = scheduleMeeting({ title: title || "Manager Check-in", participants: ["You", "Maya Chen", "Jordan Lee"], project: project || "Workspace", agenda: agenda || "Review priorities and assign next actions", scheduledAt: when || "Next available time" }); setCreateOpen(false); select(id); setTitle(""); setProject(""); setAgenda(""); setWhen(""); }

  return <div className="space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-xl font-semibold text-[var(--text-primary)]">Meeting Hub</h1><p className="mt-1 text-sm text-[var(--text-muted)]">Scheduled calls with durable agendas, notes, decisions, and follow-ups.</p></div><div className="flex gap-2"><button disabled title="Calendar sync requires integration" className={`${button} opacity-50`}><CalendarClock className="h-3.5 w-3.5" />Calendar sync requires integration</button><button onClick={() => setCreateOpen(true)} className={`${button} bg-[var(--accent)] text-white`}><Plus className="h-3.5 w-3.5" />Schedule meeting</button></div></div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_400px]"><div className="space-y-4">{Object.entries(groups).map(([label, items]) => <section key={label} className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--card-bg)] p-4"><div className="flex items-center justify-between"><h2 className="font-semibold text-[var(--text-primary)]">{label}</h2><span className="rounded-full bg-[var(--pulse-panel)] px-2 py-1 text-xs text-[var(--text-muted)]">{items.length}</span></div><div className="mt-3 grid gap-3 md:grid-cols-2">{items.map((meeting) => <article key={meeting.id} className={`rounded-xl border p-4 ${selected?.id === meeting.id ? "border-[var(--accent)]/50 bg-[var(--pulse-panel)]" : "border-[var(--border-subtle)]"}`}><button onClick={() => select(meeting.id)} className="w-full text-left"><p className="font-semibold text-[var(--text-primary)]">{meeting.title}</p><p className="mt-1 text-xs text-[var(--text-muted)]">{meeting.scheduledAt ?? "Suggested time"} · {meeting.duration}</p><p className="mt-2 line-clamp-2 text-sm text-[var(--text-secondary)]">{meeting.why}</p></button><div className="mt-3 flex flex-wrap gap-1.5">{meeting.participants.slice(0, 4).map((person) => <span key={person} className="rounded-md border border-[var(--border-subtle)] px-2 py-1 text-[10px] text-[var(--text-muted)]">{person}</span>)}</div><div className="mt-3 flex flex-wrap gap-2"><button onClick={() => join(meeting.id)} className={`${button} bg-[var(--accent)] text-white`}><Play className="h-3.5 w-3.5" />{meeting.status === "In progress" ? "Rejoin" : meeting.status === "Completed" ? "Review call" : "Join / Start"}</button><button onClick={() => generateMeetingAgenda(meeting.id)} className={button}><Sparkles className="h-3.5 w-3.5" />Agenda</button></div></article>)}</div>{!items.length ? <p className="mt-3 text-sm text-[var(--text-muted)]">No {label.toLowerCase()} meetings.</p> : null}</section>)}</div>
      {selected ? <aside className="h-fit rounded-2xl border border-[var(--border-subtle)] bg-[var(--card-bg)] p-4 xl:sticky xl:top-24"><p className="text-xs font-semibold uppercase tracking-[0.15em] text-[var(--text-muted)]">Meeting detail</p><h2 className="mt-2 text-lg font-semibold text-[var(--text-primary)]">{selected.title}</h2><p className="mt-1 text-xs text-[var(--text-muted)]">{selected.project} · {selected.duration} · {selected.status ?? "Upcoming"}</p><div className="mt-4"><p className="text-xs font-semibold text-[var(--text-muted)]">AGENDA</p><div className="mt-2 space-y-2">{(selected.generatedAgenda ?? selected.agenda).map((item) => <div key={item} className="rounded-lg border border-[var(--border-subtle)] bg-[var(--pulse-panel)] p-2 text-sm text-[var(--text-secondary)]">{item}</div>)}</div></div><div className="mt-4"><label className="text-xs font-semibold text-[var(--text-muted)]">MEETING NOTES<textarea aria-label="Meeting notes" value={selected.notes ?? ""} onChange={(event) => saveMeetingNotes(selected.id, event.target.value)} placeholder="Capture notes as the meeting runs..." className="mt-2 min-h-36 w-full resize-y rounded-xl border border-[var(--border-subtle)] bg-[var(--pulse-panel)] p-3 text-sm font-normal text-[var(--text-primary)] outline-none focus:border-[var(--accent)]/60" /></label></div><div className="mt-3 flex flex-wrap gap-2"><span className="inline-flex items-center gap-1 rounded-md border border-[var(--border-subtle)] px-2 py-1 text-xs text-[var(--text-muted)]"><Users className="h-3 w-3" />{selected.participants.length} people</span><span className="inline-flex items-center gap-1 rounded-md border border-[var(--border-subtle)] px-2 py-1 text-xs text-[var(--text-muted)]"><CheckSquare className="h-3 w-3" />{selected.followUpTaskIds?.length ?? 0} follow-ups</span></div><div className="mt-4 grid gap-2"><button onClick={() => join(selected.id)} className={`${button} bg-[var(--accent)] text-white`}><Play className="h-3.5 w-3.5" />{selected.status === "In progress" ? "Rejoin meeting" : "Join / Start meeting"}</button><button onClick={() => createMeetingFollowUpTasks(selected.id)} className={button}><CheckSquare className="h-3.5 w-3.5" />Create follow-up task</button>{selected.status === "In progress" ? <button onClick={() => endMeeting(selected.id)} className={`${button} border-red-400/20 text-red-300`}>End meeting</button> : null}{selected.status === "Completed" ? <span className="inline-flex items-center justify-center gap-2 rounded-lg bg-emerald-400/10 px-3 py-2 text-xs font-semibold text-emerald-300"><FileText className="h-3.5 w-3.5" />Notes saved</span> : null}</div></aside> : null}</div>
    {activeCallId ? <CallRoom callId={activeCallId} onClose={() => setActiveCallId(null)} onEnded={() => { if (selectedId) endMeeting(selectedId); setActiveCallId(null); }} /> : null}
    <Modal open={createOpen} onClose={() => setCreateOpen(false)} title="Schedule a meeting" description="The meeting, agenda, and participant context persist after refresh." footer={<button form="schedule-meeting-form" className="rounded-lg bg-[var(--accent)] px-4 py-2 text-sm font-semibold text-white">Schedule meeting</button>}><form id="schedule-meeting-form" onSubmit={create} className="space-y-3"><label className="block text-sm text-[var(--text-secondary)]">Title<input value={title} onChange={(event) => setTitle(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--card-bg)] px-3 outline-none" /></label><label className="block text-sm text-[var(--text-secondary)]">Project or team<input value={project} onChange={(event) => setProject(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--card-bg)] px-3 outline-none" /></label><label className="block text-sm text-[var(--text-secondary)]">Time<input type="datetime-local" value={when} onChange={(event) => setWhen(event.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--card-bg)] px-3 outline-none" /></label><label className="block text-sm text-[var(--text-secondary)]">Agenda<textarea value={agenda} onChange={(event) => setAgenda(event.target.value)} className="mt-1.5 min-h-24 w-full rounded-lg border border-[var(--border-subtle)] bg-[var(--card-bg)] p-3 outline-none" /></label><p className="text-xs text-[var(--text-muted)]">Participants: You, {members.filter((member) => member.id !== "mithilessh").slice(0, 2).map((member) => member.name).join(", ")}</p></form></Modal>
  </div>;
}
